name: Deploy Next.js application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u shakir737 -p Anilla621#
      - name: Build docker image
        run: docker build -t shakir737/ecomerse .
      - name: Publish image to docker hub
        run: docker push  shakir737/ecomerse:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull shakir737/ecomerse:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 4000:4000 --name nextjs-app-container -e MONGO_DB_URL='${{ secrets.MONGO_DB_URL }}' shakir737/ecomerse
